### ISSUE TITLE
/juju/inventory can retrieve the VIP instead of primary interface IP

### ISSUE THREAD

**Issue by yan0s** [grnet/ansible-inventory-server#13]
Request to /juju/inventory can retrieve the VIP instead of primary IP on the interface.
This would cause a problem if VIP changes during role execution, or if the role makes use of the host IP for a configuration.
eg.
juju status output:
```
keystone/0                 active    idle   1/lxd/0   10.1.0.1
keystone/1*               active    idle   2/lxd/0   10.1.0.2
keystone/2                active    idle   3/lxd/0  10.1.0.3
```
but /juju/inventory output:
```
{
  "_meta": {
    "hostvars": {
      "10.1.0.1": {},
      "10.1.0.100": {},
      "10.1.0.3": {}
    }
  },
  "openstack": {
    "children": [
      "keystone"
    ]
  },
  "keystone": {
    "hosts": [
      "10.1.0.1",
      "10.1.0.100",
      "10.1.0.3"
    ]
  }
}
```
where 10.1.0.100 is the VIP currently assigned to keystone/1.

The correct IP can be retrieved from or compared with 
```
  "network-interfaces": {
     "eth0": {
              "ip-addresses": [
                "10.1.0.2"
              ],
      }
  }
```
instead of the first IP that belongs in the given subnet from "ip_addresses" field which is currently the case.

**Comment by neoaggelos** [comment]
This has been fixed with #15 . Closing
